@startuml

title __SECURITY's Class Diagram__\n

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.security {
        class DomainUserDetailsServiceIntTest {
            {static} - USER_ONE_LOGIN : String
            {static} - USER_ONE_EMAIL : String
            {static} - USER_TWO_LOGIN : String
            {static} - USER_TWO_EMAIL : String
            {static} - USER_THREE_LOGIN : String
            {static} - USER_THREE_EMAIL : String
            - domainUserDetailsService : UserDetailsService
            + init()
            + assertThatUserCanBeFoundByLogin()
            + assertThatUserCanBeFoundByLoginIgnoreCase()
            + assertThatUserCanBeFoundByEmail()
            + assertThatUserCanNotBeFoundByEmailIgnoreCase()
            + assertThatEmailIsPrioritizedOverLogin()
            + assertThatUserNotActivatedExceptionIsThrownForNotActivatedUsers()
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.security {
        class SecurityUtilsUnitTest {
            + testgetCurrentUserLogin()
            + testgetCurrentUserJWT()
            + testIsAuthenticated()
            + testAnonymousIsNotAuthenticated()
            + testIsCurrentUserInRole()
        }
      }
    }
  }
  

  DomainUserDetailsServiceIntTest o-- UserRepository : userRepository
  DomainUserDetailsServiceIntTest o-- User : userOne
  DomainUserDetailsServiceIntTest o-- User : userTwo
  DomainUserDetailsServiceIntTest o-- User : userThree


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
