@startuml

title __SERVICE's Class Diagram__\n

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.service {
        class MailServiceIntTest {
            - jHipsterProperties : JHipsterProperties
            - messageSource : MessageSource
            - templateEngine : SpringTemplateEngine
            - javaMailSender : JavaMailSenderImpl
            - messageCaptor : ArgumentCaptor<MimeMessage>
            + setup()
            + testSendEmail()
            + testSendHtmlEmail()
            + testSendMultipartEmail()
            + testSendMultipartHtmlEmail()
            + testSendEmailFromTemplate()
            + testSendActivationEmail()
            + testCreationEmail()
            + testSendPasswordResetMail()
            + testSendEmailWithException()
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.service {
        class UserServiceIntTest {
            - auditingHandler : AuditingHandler
            ~ dateTimeProvider : DateTimeProvider
            + init()
            + assertThatUserMustExistToResetPassword()
            + assertThatOnlyActivatedUserCanRequestPasswordReset()
            + assertThatResetKeyMustNotBeOlderThan24Hours()
            + assertThatResetKeyMustBeValid()
            + assertThatUserCanResetPassword()
            + testFindNotActivatedUsersByCreationDateBefore()
            + assertThatAnonymousUserIsNotGet()
            + testRemoveNotActivatedUsers()
        }
      }
    }
  }
  

  MailServiceIntTest o-- MailService : mailService
  UserServiceIntTest o-- UserRepository : userRepository
  UserServiceIntTest o-- UserService : userService
  UserServiceIntTest o-- User : user


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
