@startuml

title __ERRORS's Class Diagram__\n

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.errors {
          class ExceptionTranslatorIntTest {
              - jacksonMessageConverter : MappingJackson2HttpMessageConverter
              - mockMvc : MockMvc
              + setup()
              + testConcurrencyFailure()
              + testMethodArgumentNotValid()
              + testParameterizedError()
              + testParameterizedError2()
              + testMissingServletRequestPartException()
              + testMissingServletRequestParameterException()
              + testAccessDenied()
              + testUnauthorized()
              + testMethodNotSupported()
              + testExceptionWithResponseStatus()
              + testInternalServerError()
          }
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.errors {
          class ExceptionTranslatorTestController {
              + concurrencyFailure()
              + methodArgument()
              + parameterizedError()
              + parameterizedError2()
              + missingServletRequestPartException()
              + missingServletRequestParameterException()
              + accessdenied()
              + unauthorized()
              + exceptionWithReponseStatus()
              + internalServerError()
          }
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.errors {
          class TestDTO {
              - test : String
              + getTest()
              + setTest()
          }
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.errors {
          class TestResponseStatusException {
          }
        }
      }
    }
  }
  

  ExceptionTranslatorIntTest o-- ExceptionTranslatorTestController : controller
  ExceptionTranslatorIntTest o-- ExceptionTranslator : exceptionTranslator
  ExceptionTranslatorTestController +-down- TestDTO
  ExceptionTranslatorTestController +-down- TestResponseStatusException


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
