@startuml

title __VM's Class Diagram__\n

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.vm {
          class KeyAndPasswordVM {
              - key : String
              - newPassword : String
              + getKey()
              + setKey()
              + getNewPassword()
              + setNewPassword()
          }
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.vm {
          class LoggerVM {
              - name : String
              - level : String
              + LoggerVM()
              + LoggerVM()
              + getName()
              + setName()
              + getLevel()
              + setLevel()
              + toString()
          }
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.vm {
          class LoginVM {
              - username : String
              - password : String
              - rememberMe : Boolean
              + getUsername()
              + setUsername()
              + getPassword()
              + setPassword()
              + isRememberMe()
              + setRememberMe()
              + toString()
          }
        }
      }
    }
  }
  

  package  {
    package com.mycompany.myapp {
      package com.mycompany.myapp.web.rest {
        package com.mycompany.myapp.web.rest.vm {
          class ManagedUserVM {
              {static} + PASSWORD_MIN_LENGTH : int
              {static} + PASSWORD_MAX_LENGTH : int
              - password : String
              + ManagedUserVM()
              + getPassword()
              + setPassword()
              + toString()
          }
        }
      }
    }
  }
  

  ManagedUserVM -up-|> UserDTO


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
